### ISSUE TITLE
Can't change the code for more than 99 features

### ISSUE THREAD

**Issue by mtukman** [Esri/playlist-storytelling-template-js#25]
The problem is that you can't modify the code to show more than 99 features.  Here is an email from Chen from ESRI support (case number 01728556)

Hello Mark,

This is Chen with ESRI support from SDK team, and I worked with Shondra here regarding your Playlist app issue. And I kind of figured out that this is a bug with this app, here is what I found:
the tricks are in the Playlist-viewer.min.js file, if you search for this.getMaxAllowablePoints=function()  in that file, and you will see, "return s" inside the function, i tried to change it to "return 100000", and it could return me all the points but the symbol is not correct, so after 99, the rest symbols will all show as 1. Because the code is not handling the maxallowablepoints correctly, however, this code is not open source, which means it is not supposed to be customized by the user, either by me, because they are not using some meaningful parameters and I could not even debug it,  so I could not hack it there. but what I can do here is to help you log in our system and also you could submit a issue in the github site where you download it, which should be :
https://github.com/Esri/playlist-storytelling-template-js, and click on the issues tab, and "New Issue", this way it might be noticed earlier. 

Thank you,

Chen
Esri Support Services

**Comment by ssylvia** [comment]
The default code only supports 99 points because there are only 99 icons included with the app. If you would like to use more, download the source version of the app (on this repo), then you will need to write a new renderer that supports either non-numbered points or supply more icons. Then build the app for production again.

https://geonet.esri.com/message/372512#372512

**Comment by mtukman** [comment]
Thanks Stephen.   I changed the renderer so that it just uses one icon and it looks right at localhost:4567.  Then I do a ‘bundle exec middleman build’, which runs fine.  I then copy the deploy folder to my server, but it’s still  using the numbered icons.

Any ideas?  Thanks.

Mark
707.206.6290

**Comment by ssylvia** [comment]
I wouldn't be able to tell without seeing how everything ran. Did everything build correctly? Also, make sure to clear your cache to be sure you're not getting an old version of the code.

**Comment by mtukman** [comment]
Thanks for your help Stephen.  After clearing the browser cache, I get the words ‘loading playlist’ without a spinning wheel.

No errors from the build that I can see and the middleman site looks right.

Mark

**Comment by ssylvia** [comment]
Do you have a url to share? Are there errors in the console.

**Comment by mtukman** [comment]
Stephen:

URL:

Gis.tukmangeospatial.net/PI

I also attached the mapconfig, so that you can see it – I just set the icon to a single png file.

Mark

**Comment by ssylvia** [comment]
It doesn’t look like the JavaScript file is getting built or it’s not accessible from the server.
